# Generated by Django 5.2.1 on 2025-05-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=500)),
                ('emp_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
    ]
